### PR TITLE
Feat/show popular articles

### LINKED ISSUE #7: Show top posts
To show top posts we need to get all the posts and sort them out by reaction/popularity

### LINKED ISSUE #31: [enhancement] make the *go to user's dashboard* button more specifying
### What would you like to share?

the current style doesn't feel good and users can be confused due to that, so it's better to make it look like a button instead

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AnishDe12020**
## What does this PR fix?

Closes #7 

## Proposed Changes

- [x] Retrieve all posts of the user
- [x] Sort posts by reactions 
- [x] Make changes to types and refactor all code
- [x] Show only top 3 posts 

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All tests have passed.

### CODE REVIEW

**Review by carrotfarmer — COMMENTED** [review]
@AnishDe12020 Can we have a separate section for the top posts? The top posts are currently being displayed under the recent section. Plus we can limit the number of top posts shown (perhaps 3-5?). Great job btw!

**Comment by avneesh0612** [comment]
Yeah, that would be cool :)

**Review by avneesh0612 — COMMENTED** [review]
Hey, just change the title and display 3 top posts :)

**Review by carrotfarmer — APPROVED** [review]
LGTM!

**Review by avneesh0612 — COMMENTED** [review]
LGTM 🚀

**Pull request merged**
