### PR TITLE
refactor: clean code

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What does this PR fix?

Cleans your ugly code

## Proposed Changes
- Refactors

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All tests have passed.

## Screenshots
N/A

## Additional Info
N/A

### CODE REVIEW

**Review by avneesh0612 — COMMENTED** [review]
Hey, the build is failing-

image

**Comment by carrotfarmer** [comment]
Make the return type a promise of PostType

**Comment by carrotfarmer** [comment]
Ah never mind!

**Review by avneesh0612 — APPROVED** [review]
LGTM 🚀 thanks!

**Pull request merged**
