### PR TITLE
feat: cache posts

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What does this PR fix?

Caches posts

## Proposed Changes
- Caching posts for faster loads

## Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All tests have passed.

## Screenshots
N/A

## Additional Info
N/A

### CODE REVIEW

**Review by avneesh0612 — COMMENTED** [review]
image

build failing again 👀

**Comment by carrotfarmer** [comment]
@SiddharthShyniben Here, after the posts are cached
image
I think if you return the posts array the error will be fixed.

**Comment by SiddharthShyniben** [comment]
ah my bad f

**Review by avneesh0612 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
